name: Unity Build and Test

on:
  push:
    branches:
      - main  # or your main development branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Unity
        uses: game-ci/unity-setup@v2
        with:
          unityVersion: 2022.3.43f1 # specify your Unity version

      - name: Test Unity Project
        uses: game-ci/unity-test-runner@v3
        with:
          unityVersion: 2022.3.43f1 # specify your Unity version
          testMode: playmode # run playmode tests
          testResults: test-results.xml # output results file

      - name: Build Unity Project
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: 2021.3.11f1 # specify your Unity version
          targetPlatform: StandaloneOSX # macOS build, adjust if targeting Windows or others
          
      - name: Notify Discord
        if: always() # This step will run regardless of success or failure of the build steps
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d "{\"username\": \"GitHub Actions\", \"content\": \"Build for ${{ github.repository }} on branch ${{ github.ref }} completed with status: ${{ job.status }}.\"}" \
          ${{ secrets.DISCORD_WEBHOOK_URL }}

